name: Build Release APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Generate App Icons
        run: dart run flutter_launcher_icons

      - name: Build Split APKs
        run: flutter build apk --release --split-per-abi

      - name: Rename APKs
        run: |
          mkdir -p build/release-apks
          cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/release-apks/Livelife-arm64-v8a.apk
          cp build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk build/release-apks/Livelife-armeabi-v7a.apk
          cp build/app/outputs/flutter-apk/app-x86_64-release.apk build/release-apks/Livelife-x86_64.apk

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Livelife-Release-APKs
          path: build/release-apks/*.apk

      - name: Build Web
        run: flutter build web --release --base-href "/sanjid-app-flutter-model-/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web

      - name: Create Release & Upload APKs
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/release-apks/*.apk"
          tag: "v1.0.${{ github.run_number }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
